
/*
 * This file is generated by the HRTF processor. Do not edit.
 */


#pragma once

#include <array>
#include <cstddef>

namespace synthizer::hrtf_data {

typedef std::array<std::array<float, 16>, 710> ImpulseArray;
extern const ImpulseArray IMPULSES;
const std::size_t IMPULSE_LENGTH = 16;

struct ElevationDef {
    double angle;
    /*
     * Where the impulses start in the big array.
     */
    std::size_t azimuth_start;
    std::size_t azimuth_count;
};

extern const std::array<ElevationDef, 14> ELEVATIONS;

}