#pragma once

#ifdef __cplusplus
extern "C" {
#endif 

enum SYZ_PANNER_STRATEGY {
	SYZ_PANNER_STRATEGY_HRTF = 0,
	SYZ_PANNER_STRATEGY_STEREO = 1,
	SYZ_PANNER_STRATEGY_COUNT,
};

/*
 * Distance models, modeled after the WebAudio spec.
 * */
enum SYZ_DISTANCE_MODEL {
	SYZ_DISTANCE_MODEL_NONE,
	SYZ_DISTANCE_MODEL_LINEAR,
	SYZ_DISTANCE_MODEL_EXPONENTIAL,
	SYZ_DISTANCE_MODEL_INVERSE,
	SYZ_DISTANCE_MODEL_COUNT,
};

enum SYZ_NOISE_TYPE {
	SYZ_NOISE_TYPE_UNIFORM,
	SYZ_NOISE_TYPE_VM,
	SYZ_NOISE_TYPE_FILTERED_BROWN,
	SYZ_NOISE_TYPE_COUNT,
};

enum SYZ_PROPERTIES {
	SYZ_P_AZIMUTH,
	SYZ_P_BUFFER,
	SYZ_P_CLOSENESS_BOOST,
	SYZ_P_CLOSENESS_BOOST_DISTANCE,
	SYZ_P_DISTANCE_MAX,
	SYZ_P_DISTANCE_MODEL,
	SYZ_P_DISTANCE_REF,
	SYZ_P_ELEVATION,
	SYZ_P_GAIN,
	SYZ_P_PANNER_STRATEGY,
	SYZ_P_PANNING_SCALAR,
	SYZ_P_POSITION,
	SYZ_P_ORIENTATION,
	SYZ_P_ROLLOFF,

	SYZ_P_LOOPING,

	SYZ_P_NOISE_TYPE,

	SYZ_P_PITCH_BEND,
};

#ifdef __cplusplus
}
#endif
